---
- hosts: all
  vars:
    users: ['user1', 'user2']
    user_password_valid_time: 30
  tasks:
      
    - name: set users password valid time
      shell: chage -M "{{ user_password_valid_time }}" "{{ item['item'] }}"






    - name: change password for root user
      become: true # do this as root
      user:
        name: root
        password: "{{ password_hash.stdout_lines[-1] }}"
